version: '3'

services:
    web:
        container_name: "cars_web"
        build:
            context: ./cars
            dockerfile: Dockerfile.dev
        volumes:
            - ./cars:/code
        ports:
            - "8000:8000"
        env_file:
            - ./postgres.env
            - ./django.env

    db:
        container_name: "cars_db"
        image: postgres:12-alpine
        expose:
            - "5432"
        env_file:
            - ./postgres.env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        
volumes:
    postgres-data: