version: '3'

services:
    web:
        container_name: "cars_web"
        build:
            context: .
            dockerfile: dockerfile.dev
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file:
            - ./postgres.env
            - ./django.env

    db:
        container_name: "cars_db"
        image: postgres:12-alpine
        expose:
            - "5432"
        env_file:
            - ./postgres.env
        