# Generated by Django 3.1 on 2020-08-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars_app", "0002_carrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrate",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="cars_app.car",
            ),
        ),
    ]
